// <auto-generated />
using System;
using DemoAppDotNet7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoAppDotNet7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231119021323_AddImagePathPropForTblEmployee")]
    partial class AddImagePathPropForTblEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoAppDotNet7.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("CourseId");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Mathmatics",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Physics",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Chemistry",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Biology",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "CS-50",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("DepartmentNumber")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Managing department"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Financial department"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "IT department"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "HRs department"
                        });
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("HireDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "zaid@g.com",
                            FirstName = "zaid",
                            HireDate = new DateTime(2023, 11, 19, 5, 13, 23, 196, DateTimeKind.Local).AddTicks(8902),
                            IsDeleted = false,
                            LastName = "albaik",
                            PhoneNumber = "0790000000",
                            Salary = 1000f
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "ali@g.com",
                            FirstName = "ali",
                            HireDate = new DateTime(2023, 11, 19, 5, 13, 23, 196, DateTimeKind.Local).AddTicks(8937),
                            IsDeleted = false,
                            LastName = "albaik",
                            PhoneNumber = "0790000000",
                            Salary = 2000f
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "ahmad@g.com",
                            FirstName = "ahmad",
                            HireDate = new DateTime(2023, 11, 19, 5, 13, 23, 196, DateTimeKind.Local).AddTicks(8939),
                            IsDeleted = false,
                            LastName = "albaik",
                            PhoneNumber = "0790000000",
                            Salary = 3000f
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Email = "mohammad@g.com",
                            FirstName = "mohammad",
                            HireDate = new DateTime(2023, 11, 19, 5, 13, 23, 196, DateTimeKind.Local).AddTicks(8941),
                            IsDeleted = false,
                            LastName = "albaik",
                            PhoneNumber = "0790000000",
                            Salary = 4000f
                        });
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("InstractorId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique()
                        .HasFilter("[OfficeId] IS NOT NULL");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abdullah",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yasmeen",
                            OfficeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hassan",
                            OfficeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ali",
                            OfficeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ali",
                            OfficeId = 5
                        });
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zaid Albaik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "test Albaik"
                        },
                        new
                        {
                            Id = 3,
                            Name = "waled Albaik"
                        },
                        new
                        {
                            Id = 4,
                            Name = "soso Albaik"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kamal Albaik"
                        });
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Result", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstractorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OffeceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SectionId");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Sections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            InstructorId = 1,
                            SectionName = "S_MA1"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            InstructorId = 2,
                            SectionName = "S_MA2"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            InstructorId = 3,
                            SectionName = "S_PH2"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            InstructorId = 4,
                            SectionName = "S_BI1"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            InstructorId = 5,
                            SectionName = "S_BI2"
                        });
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.TestViewGetEmployees", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasIndex("DepartmentId");

                    b.ToTable((string)null);

                    b.ToView("SelectAllEmployees", (string)null);
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Employee", b =>
                {
                    b.HasOne("DemoAppDotNet7.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("DepartmentId_FK");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Instructor", b =>
                {
                    b.HasOne("DemoAppDotNet7.Models.Office", "Office")
                        .WithOne("Instructor")
                        .HasForeignKey("DemoAppDotNet7.Models.Instructor", "OfficeId");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Section", b =>
                {
                    b.HasOne("DemoAppDotNet7.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoAppDotNet7.Models.Instructor", "Instructor")
                        .WithMany("Sections")
                        .HasForeignKey("InstructorId");

                    b.OwnsOne("DemoAppDotNet7.Models.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<int>("SectionId")
                                .HasColumnType("int");

                            b1.Property<TimeSpan?>("EndTime")
                                .HasColumnType("time")
                                .HasColumnName("EndTime");

                            b1.Property<TimeSpan?>("StartTime")
                                .HasColumnType("time")
                                .HasColumnName("StartTime");

                            b1.HasKey("SectionId");

                            b1.ToTable("Sections");

                            b1.WithOwner()
                                .HasForeignKey("SectionId");
                        });

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.TestViewGetEmployees", b =>
                {
                    b.HasOne("DemoAppDotNet7.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Instructor", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("DemoAppDotNet7.Models.Office", b =>
                {
                    b.Navigation("Instructor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
